#!/bin/bash

set -euf -o pipefail

dir=$(dirname "$0")

if test "$#" != 3; then
	echo "Usage error" >&2
	exit 1
fi

exec "$dir/rzbackup" decrypt \
	--repository "$1" \
	--password-file "$2" \
	--file-name "$3"

# ex: noet ts=4 filetype=sh
