// WARNING: this file is generated by build.rs, changes will be lost.

pub const VERSION: & 'static str = "3.3.0";
pub const AUTHOR: & 'static str = "James Pharaoh <james@pharaoh.uk>";

// ex: noet ts=4 filetype=rust
